services:
  graphcast:
    build:
      context: .
      dockerfile: ./graphcast_image/Dockerfile
    image: debian-mamba:latest
    working_dir: /graphcast_model
    volumes:
      - ./graphcast_model:/app
    # Runs inside the conda env thanks to the ENTRYPOINT
    command: ["python", "main.py"]
    environment:
      PYTHONUNBUFFERED: "1"

  gfs:
    build:
      context: .
      dockerfile: ./wgrib_image/Dockerfile
    image: debian-wgrib:latest
    working_dir: /gfs_model
    volumes:
      - ./gfs_model:/app
    command: ["bash", "gfs-prepare"]
  